#!/usr/bin/env python3
"""
Regenerate intelligence/config.history.json: every config.yaml ever shipped.

The service mounts the checkout's intelligence/config.yaml at /app/legacy
to carry over settings that older versions told users to edit there. The
checkout and the image are often different versions ('git pull' follows
the main branch, ARSSE_VERSION=latest the last release), so a file that
equals any committed version of the reference is not an edit and must not
override the image's settings (config._read_legacy_edits).

Run this after changing intelligence/config.yaml; the unit test
test_current_reference_is_in_the_history fails until then. Entries already
in the file are kept, so a shallow clone never drops old references.

Usage: scripts/config-history.py [--check]
    --check  only report whether the file is up to date (exit 1 if not)
"""

import argparse
import json
import subprocess
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / 'intelligence'))

from config import CONFIG_HISTORY_NAME, flatten_reference  # noqa: E402

REFERENCE = 'intelligence/config.yaml'
HISTORY = ROOT / 'intelligence' / CONFIG_HISTORY_NAME


def git(*args: str) -> str:
    return subprocess.run(['git', '-C', str(ROOT), *args], check=True,
                          capture_output=True, text=True).stdout


def committed_references() -> list:
    """(commit, flattened settings) for every commit that changed the file, oldest first."""
    commits = git('log', '--reverse', '--format=%h', '--', REFERENCE).split()
    return [(commit, flatten_reference(yaml.safe_load(git('show', f'{commit}:{REFERENCE}'))))
            for commit in commits]


def build() -> dict:
    try:
        entries = json.loads(HISTORY.read_text(encoding='utf-8'))['references']
    except FileNotFoundError:
        entries = []
    current = flatten_reference(yaml.safe_load((ROOT / REFERENCE).read_text(encoding='utf-8')))
    for commit, settings in committed_references() + [('uncommitted', current)]:
        known = [entry for entry in entries if entry['settings'] == settings]
        if not known:
            entries.append({'commit': commit, 'settings': settings})
        elif known[0]['commit'] == 'uncommitted' and commit != 'uncommitted':
            known[0]['commit'] = commit
    return {
        '_comment': 'Every intelligence/config.yaml ever committed, flattened; '
                    'generated by scripts/config-history.py, do not edit.',
        'references': entries,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    text = json.dumps(build(), indent=1, ensure_ascii=False) + '\n'
    if args.check:
        up_to_date = HISTORY.exists() and HISTORY.read_text(encoding='utf-8') == text
        print(f'{HISTORY.name} is {"up to date" if up_to_date else "outdated"}')
        return 0 if up_to_date else 1
    HISTORY.write_text(text, encoding='utf-8')
    print(f'{HISTORY.name}: {len(json.loads(text)["references"])} references')
    return 0


if __name__ == '__main__':
    sys.exit(main())
